### ISSUE TITLE
Not working 100%

### ISSUE THREAD

**Issue by divanvb** [platosha/angular2-polymer-quickstart#10] opened 2016-12-04 04:05 UTC
Hi

So I cloned this project, ran npm install and bower install. The project is running fine, there are just some bugs such as color for example. The primary color from the project isn't applied so I get a standard white project instead of the color theme that is applied.

Any suggestion how I might fix this?

**Comment by platosha** [comment] 2016-12-05 08:46
@divanvb Hi! This is a regression due to https://github.com/vaadin/angular2-polymer/issues/104

Unfortunately, fixing the above issue in the `@vaadin/angular2-polymer` library is not easy and quick, not possible for us until next year at least.

As a workaround, you can either downgrade Angular to v2.1 or below, or move the styles from the Angular components to the `index.html` file using the following syntax:
```html
<style is="custom-style">
  app-toolbar {
    background: var(--primary-color);
    color: var(--dark-theme-text-color);
  }
</style>
```

**Comment by juhopiirainen** [comment] 2019-07-05 08:44
Repository is archived, closing this issue.

**Closed as completed by juhopiirainen** 2019-07-05 08:44 UTC
